document.querySelector('#containerbackground').classList.add('backgroundgray')

document.querySelector('#graycircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundgray')
})

document.querySelector('#redcircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundred')
})

document.querySelector('#orangecircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundorange')
})

document.querySelector('#yellowcircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundyellow')
})

document.querySelector('#greencircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundgreen')
})

document.querySelector('#cyancircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundcyan')
})

document.querySelector('#bluecircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundblue')
})

document.querySelector('#purplecircle').addEventListener('click', () => {
    document.querySelector('#containerbackground').classList.remove('backgroundgray')
    document.querySelector('#containerbackground').classList.remove('backgroundred')
    document.querySelector('#containerbackground').classList.remove('backgroundorange')
    document.querySelector('#containerbackground').classList.remove('backgroundyellow')
    document.querySelector('#containerbackground').classList.remove('backgroundgreen')
    document.querySelector('#containerbackground').classList.remove('backgroundcyan')
    document.querySelector('#containerbackground').classList.remove('backgroundblue')
    document.querySelector('#containerbackground').classList.remove('backgroundpurple')
    document.querySelector('#containerbackground').classList.add('backgroundpurple')
})